wallpaper {
    monitor = DP-1
    path = ~/Pictures/Wallpapers/LP.png
    fit_mode = fill
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/Wallpapers/black.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpapers/black.png
    fit_mode = cover
}

splash = false