# #######################################################################################
# Belly Hyprland Config
# #######################################################################################

# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = wofi --show drun

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

######################
### SEPERATE FILES ###
######################
source = ~/.config/hypr/hyprModules/animations.conf
source = ~/.config/hypr/hyprModules/autostart.conf
source = ~/.config/hypr/hyprModules/decoration.conf
source = ~/.config/hypr/hyprModules/env.conf
source = ~/.config/hypr/hyprModules/general.conf
source = ~/.config/hypr/hyprModules/input.conf
source = ~/.config/hypr/hyprModules/keybinds.conf
source = ~/.config/hypr/hyprModules/layout.conf
source = ~/.config/hypr/hyprModules/misc.conf
source = ~/.config/hypr/hyprModules/monitors.conf
source = ~/.config/hypr/hyprModules/windowrules.conf